apiVersion: v1
kind: Service
metadata:
  name: ms-pedidos-lb
  namespace: microservicios
  labels:
    app: ms-pedidos
spec:
  selector:
    app: ms-pedidos
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
