apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-config
  namespace: microservicios
  labels:
    app.kubernetes.io/managed-by: kubectl
data:
  DB_HOST: "aws-1-us-west-2.pooler.supabase.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SSL_MODE: "require"
  PRODUCTOS_SERVICE_URL: "http://ms-productos-svc:8081"
