server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-pedidos

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:aws-1-us-west-2.pooler.supabase.com}:${DB_PORT:5432}/${DB_NAME:postgres}?sslMode=${DB_SSL_MODE:require}
    username: ${DB_USER:postgres.cssspmgceglbkvfmhels}
    password: ${DB_PASSWORD:!Llampier29}