apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-productos
  namespace: microservicios
  labels:
    app: ms-productos
    version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-productos
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-productos
        version: "1.0"
    spec:
      containers:
        - name: ms-productos
          image: llampier2/ms-productos:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "8081"
          envFrom:
            - configMapRef:
                name: ms-config
            - secretRef:
                name: ms-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3
